name: pharma_ai
description: Application de gestion de pharmacie intelligente avec ML Kit.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ML Kit
  google_mlkit_text_recognition: ^0.13.0
  google_mlkit_barcode_scanning: ^0.12.0
  google_mlkit_language_id: ^0.10.0

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.0.0
  google_sign_in: ^6.2.1

  # Navigation & State
  go_router: ^13.0.0
  flutter_riverpod: ^2.5.0

  # Localisation
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Médias
  image_picker: ^1.1.0
  camera: ^0.10.0

  # UX
  audioplayers: ^6.0.0
  vibration: ^2.0.0
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.0

  # UI
  fl_chart: ^0.68.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true          # ← AJOUTÉ : active la génération de AppLocalizations
  uses-material-design: true